export enum DomainSignal {
  // Fallback
  NONE = "NONE",

  // Belastning / regulering
  STRESS_REFERENCE = "STRESS_REFERENCE",
  ANXIETY_REFERENCE = "ANXIETY_REFERENCE",
  REGULATION_REQUEST = "REGULATION_REQUEST",

  // Frygt / fobi
  PHOBIA_REFERENCE = "PHOBIA_REFERENCE",

  // Traume og højrisiko
  TRAUMA_REFERENCE = "TRAUMA_REFERENCE",
  PTSD_REFERENCE = "PTSD_REFERENCE",
  ADDICTION_REFERENCE = "ADDICTION_REFERENCE",
  SELF_HARM_SIGNAL = "SELF_HARM_SIGNAL",

  // Hukommelse / identitet
  MEMORY_MANIPULATION_REQUEST = "MEMORY_MANIPULATION_REQUEST",
  IDENTITY_MANIPULATION_REQUEST = "IDENTITY_MANIPULATION_REQUEST",

  // Behandling / garanti / substitution
  TREATMENT_SUBSTITUTION_REQUEST = "TREATMENT_SUBSTITUTION_REQUEST",
  TREATMENT_GUARANTEE_REQUEST = "TREATMENT_GUARANTEE_REQUEST",

  // Sikkerhed / kontrol
  SAFETY_CONCERN = "SAFETY_CONCERN",
  LOSS_OF_CONTROL_CONCERN = "LOSS_OF_CONTROL_CONCERN",

  // Praktisk
  PRACTICAL_QUERY = "PRACTICAL_QUERY"
}
