export enum DomainSignal {
  NONE = "NONE",

  STRESS = "STRESS",
  REGULATION_REQUEST = "REGULATION_REQUEST",

  TRAUMA_REFERENCE = "TRAUMA_REFERENCE",
  PTSD_REFERENCE = "PTSD_REFERENCE",

  SELF_HARM_SIGNAL = "SELF_HARM_SIGNAL",
  SUICIDAL_IDEATION = "SUICIDAL_IDEATION",

  AMBIGUOUS_VULNERABILITY = "AMBIGUOUS_VULNERABILITY",
}
